name: Build Docker image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DOCKER_IMAGE_NAME: felixdumais1/tractolearn-docker:$(date +%Y-%m-%d-%H-%M)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        tags: ${{ env.DOCKER_IMAGE_NAME }}
